//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int id { get; set; }
        public string image1 { get; set; }
        public string note { get; set; }
        public Nullable<int> ImageLibraryId { get; set; }
    
        public virtual ImageLibrary ImageLibrary { get; set; }
    }
}
